#include "efxpresetsregistry.h"
#include "snd_local.h"

EfxPresetsRegistry EfxPresetsRegistry::s_instance;

// This is a common supertype for all presets that are declared globally
// and link themselves to the global presets cache
// (so we do not have to maintain an array of presets and its length manually)
struct EfxPresetEntry {
	const wsw::HashedStringView name;
	EfxPresetEntry *nextInHashBin { nullptr };
	EFXEAXREVERBPROPERTIES preset {};

	explicit EfxPresetEntry( const char *presetMacroName ) noexcept
		: name( presetMacroName + sizeof( "EFX_REVERB_PRESET_" ) - 1 ) {
		const auto binIndex = name.getHash() % EfxPresetsRegistry::kNumHashBins;
		this->nextInHashBin = EfxPresetsRegistry::s_instance.m_hashBins[binIndex];
		EfxPresetsRegistry::s_instance.m_hashBins[binIndex] = this;
	}
};

auto EfxPresetsRegistry::findByName( const wsw::StringView &name ) const -> const EFXEAXREVERBPROPERTIES * {
	return findByName( wsw::HashedStringView( name ) );
}

auto EfxPresetsRegistry::findByName( const wsw::HashedStringView &name ) const -> const EFXEAXREVERBPROPERTIES * {
	const auto binIndex = name.getHash() % kNumHashBins;
	for( EfxPresetEntry *entry = m_hashBins[binIndex]; entry; entry = entry->nextInHashBin ) {
		if( entry->name.equalsIgnoreCase( name ) ) {
			return &entry->preset;
		}
	}
	return nullptr;
}

#define DEFINE_PRESET( presetMacroName )                                                    \
	static struct EfxPresetsEntry_##presetMacroName : public EfxPresetEntry {               \
		EfxPresetsEntry_##presetMacroName() noexcept : EfxPresetEntry( #presetMacroName ) { \
			this->preset = presetMacroName;                                                 \
    	}                                                                                   \
	} presetEntry_##presetMacroName;

// cat efx-presets.h | grep EFX_REV | awk '{b = sprintf("DEFINE_PRESET( %s );", $2); print b}'

DEFINE_PRESET( EFX_REVERB_PRESET_GENERIC );
DEFINE_PRESET( EFX_REVERB_PRESET_PADDEDCELL );
DEFINE_PRESET( EFX_REVERB_PRESET_ROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_BATHROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_LIVINGROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_STONEROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_AUDITORIUM );
DEFINE_PRESET( EFX_REVERB_PRESET_CONCERTHALL );
DEFINE_PRESET( EFX_REVERB_PRESET_CAVE );
DEFINE_PRESET( EFX_REVERB_PRESET_ARENA );
DEFINE_PRESET( EFX_REVERB_PRESET_HANGAR );
DEFINE_PRESET( EFX_REVERB_PRESET_CARPETEDHALLWAY );
DEFINE_PRESET( EFX_REVERB_PRESET_HALLWAY );
DEFINE_PRESET( EFX_REVERB_PRESET_STONECORRIDOR );
DEFINE_PRESET( EFX_REVERB_PRESET_ALLEY );
DEFINE_PRESET( EFX_REVERB_PRESET_FOREST );
DEFINE_PRESET( EFX_REVERB_PRESET_CITY );
DEFINE_PRESET( EFX_REVERB_PRESET_MOUNTAINS );
DEFINE_PRESET( EFX_REVERB_PRESET_QUARRY );
DEFINE_PRESET( EFX_REVERB_PRESET_PLAIN );
DEFINE_PRESET( EFX_REVERB_PRESET_PARKINGLOT );
DEFINE_PRESET( EFX_REVERB_PRESET_SEWERPIPE );
DEFINE_PRESET( EFX_REVERB_PRESET_UNDERWATER );
DEFINE_PRESET( EFX_REVERB_PRESET_DRUGGED );
DEFINE_PRESET( EFX_REVERB_PRESET_DIZZY );
DEFINE_PRESET( EFX_REVERB_PRESET_PSYCHOTIC );
DEFINE_PRESET( EFX_REVERB_PRESET_CASTLE_SMALLROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_CASTLE_SHORTPASSAGE );
DEFINE_PRESET( EFX_REVERB_PRESET_CASTLE_MEDIUMROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_CASTLE_LARGEROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_CASTLE_LONGPASSAGE );
DEFINE_PRESET( EFX_REVERB_PRESET_CASTLE_HALL );
DEFINE_PRESET( EFX_REVERB_PRESET_CASTLE_CUPBOARD );
DEFINE_PRESET( EFX_REVERB_PRESET_CASTLE_COURTYARD );
DEFINE_PRESET( EFX_REVERB_PRESET_CASTLE_ALCOVE );
DEFINE_PRESET( EFX_REVERB_PRESET_FACTORY_SMALLROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_FACTORY_SHORTPASSAGE );
DEFINE_PRESET( EFX_REVERB_PRESET_FACTORY_MEDIUMROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_FACTORY_LARGEROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_FACTORY_LONGPASSAGE );
DEFINE_PRESET( EFX_REVERB_PRESET_FACTORY_HALL );
DEFINE_PRESET( EFX_REVERB_PRESET_FACTORY_CUPBOARD );
DEFINE_PRESET( EFX_REVERB_PRESET_FACTORY_COURTYARD );
DEFINE_PRESET( EFX_REVERB_PRESET_FACTORY_ALCOVE );
DEFINE_PRESET( EFX_REVERB_PRESET_ICEPALACE_SMALLROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_ICEPALACE_SHORTPASSAGE );
DEFINE_PRESET( EFX_REVERB_PRESET_ICEPALACE_MEDIUMROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_ICEPALACE_LARGEROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_ICEPALACE_LONGPASSAGE );
DEFINE_PRESET( EFX_REVERB_PRESET_ICEPALACE_HALL );
DEFINE_PRESET( EFX_REVERB_PRESET_ICEPALACE_CUPBOARD );
DEFINE_PRESET( EFX_REVERB_PRESET_ICEPALACE_COURTYARD );
DEFINE_PRESET( EFX_REVERB_PRESET_ICEPALACE_ALCOVE );
DEFINE_PRESET( EFX_REVERB_PRESET_SPACESTATION_SMALLROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_SPACESTATION_SHORTPASSAGE );
DEFINE_PRESET( EFX_REVERB_PRESET_SPACESTATION_MEDIUMROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_SPACESTATION_LARGEROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_SPACESTATION_LONGPASSAGE );
DEFINE_PRESET( EFX_REVERB_PRESET_SPACESTATION_HALL );
DEFINE_PRESET( EFX_REVERB_PRESET_SPACESTATION_CUPBOARD );
DEFINE_PRESET( EFX_REVERB_PRESET_SPACESTATION_ALCOVE );
DEFINE_PRESET( EFX_REVERB_PRESET_WOODEN_SMALLROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_WOODEN_SHORTPASSAGE );
DEFINE_PRESET( EFX_REVERB_PRESET_WOODEN_MEDIUMROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_WOODEN_LARGEROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_WOODEN_LONGPASSAGE );
DEFINE_PRESET( EFX_REVERB_PRESET_WOODEN_HALL );
DEFINE_PRESET( EFX_REVERB_PRESET_WOODEN_CUPBOARD );
DEFINE_PRESET( EFX_REVERB_PRESET_WOODEN_COURTYARD );
DEFINE_PRESET( EFX_REVERB_PRESET_WOODEN_ALCOVE );
DEFINE_PRESET( EFX_REVERB_PRESET_SPORT_EMPTYSTADIUM );
DEFINE_PRESET( EFX_REVERB_PRESET_SPORT_SQUASHCOURT );
DEFINE_PRESET( EFX_REVERB_PRESET_SPORT_SMALLSWIMMINGPOOL );
DEFINE_PRESET( EFX_REVERB_PRESET_SPORT_LARGESWIMMINGPOOL );
DEFINE_PRESET( EFX_REVERB_PRESET_SPORT_GYMNASIUM );
DEFINE_PRESET( EFX_REVERB_PRESET_SPORT_FULLSTADIUM );
DEFINE_PRESET( EFX_REVERB_PRESET_SPORT_STADIUMTANNOY );
DEFINE_PRESET( EFX_REVERB_PRESET_PREFAB_WORKSHOP );
DEFINE_PRESET( EFX_REVERB_PRESET_PREFAB_SCHOOLROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_PREFAB_PRACTISEROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_PREFAB_OUTHOUSE );
DEFINE_PRESET( EFX_REVERB_PRESET_PREFAB_CARAVAN );
DEFINE_PRESET( EFX_REVERB_PRESET_DOME_TOMB );
DEFINE_PRESET( EFX_REVERB_PRESET_PIPE_SMALL );
DEFINE_PRESET( EFX_REVERB_PRESET_DOME_SAINTPAULS );
DEFINE_PRESET( EFX_REVERB_PRESET_PIPE_LONGTHIN );
DEFINE_PRESET( EFX_REVERB_PRESET_PIPE_LARGE );
DEFINE_PRESET( EFX_REVERB_PRESET_PIPE_RESONANT );
DEFINE_PRESET( EFX_REVERB_PRESET_OUTDOORS_BACKYARD );
DEFINE_PRESET( EFX_REVERB_PRESET_OUTDOORS_ROLLINGPLAINS );
DEFINE_PRESET( EFX_REVERB_PRESET_OUTDOORS_DEEPCANYON );
DEFINE_PRESET( EFX_REVERB_PRESET_OUTDOORS_CREEK );
DEFINE_PRESET( EFX_REVERB_PRESET_OUTDOORS_VALLEY );
DEFINE_PRESET( EFX_REVERB_PRESET_MOOD_HEAVEN );
DEFINE_PRESET( EFX_REVERB_PRESET_MOOD_HELL );
DEFINE_PRESET( EFX_REVERB_PRESET_MOOD_MEMORY );
DEFINE_PRESET( EFX_REVERB_PRESET_DRIVING_COMMENTATOR );
DEFINE_PRESET( EFX_REVERB_PRESET_DRIVING_PITGARAGE );
DEFINE_PRESET( EFX_REVERB_PRESET_DRIVING_INCAR_RACER );
DEFINE_PRESET( EFX_REVERB_PRESET_DRIVING_INCAR_SPORTS );
DEFINE_PRESET( EFX_REVERB_PRESET_DRIVING_INCAR_LUXURY );
DEFINE_PRESET( EFX_REVERB_PRESET_DRIVING_FULLGRANDSTAND );
DEFINE_PRESET( EFX_REVERB_PRESET_DRIVING_EMPTYGRANDSTAND );
DEFINE_PRESET( EFX_REVERB_PRESET_DRIVING_TUNNEL );
DEFINE_PRESET( EFX_REVERB_PRESET_CITY_STREETS );
DEFINE_PRESET( EFX_REVERB_PRESET_CITY_SUBWAY );
DEFINE_PRESET( EFX_REVERB_PRESET_CITY_MUSEUM );
DEFINE_PRESET( EFX_REVERB_PRESET_CITY_LIBRARY );
DEFINE_PRESET( EFX_REVERB_PRESET_CITY_UNDERPASS );
DEFINE_PRESET( EFX_REVERB_PRESET_CITY_ABANDONED );
DEFINE_PRESET( EFX_REVERB_PRESET_DUSTYROOM );
DEFINE_PRESET( EFX_REVERB_PRESET_CHAPEL );
DEFINE_PRESET( EFX_REVERB_PRESET_SMALLWATERROOM );
